import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import colors from "../data/colors.json";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Colors of the year</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {colors.map((color) => (
        <Link href={`/${color.name}`}>
          <h2>{color.name}</h2>
        </Link>
      ))}
    </div>
  );
}
